global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ledger Gateway
  - job_name: 'ledger-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  # Ledger Switch
  - job_name: 'ledger-switch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['switch:8081']

  # Ledger Bank (Axis)
  - job_name: 'ledger-bank-axis'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bank-axis:8070']
